"""Static report labels; source excerpts and company clauses are preserved verbatim."""

# key: Russian, Uzbek, English
TEXT = {
    "date": ("Дата", "Sana", "Date"),
    "author": ("Автор", "Muallif", "Author"),
    "insured_sum": ("Страховая сумма", "Sug‘urta summasi", "Insured sum"),
    "object_value": ("Стоимость объекта", "Obyekt qiymati", "Object value"),
    "region": ("Регион", "Hudud", "Region"),
    "term_days": ("Срок, дней", "Muddat, kun", "Term, days"),
    "object_description": ("Объект страхования", "Sug‘urta obyekti", "Insured object"),
    "minimum_rate": ("Минимальная ставка, %", "Eng kam stavka, %", "Minimum rate, %"),
    "recommended_rate": ("Рекомендуемая ставка, %", "Tavsiya etilgan stavka, %", "Recommended rate, %"),
    "annualized_rate": ("Годовой эквивалент, %", "Yillik ekvivalent, %", "Annual equivalent, %"),
    "annual_market_rate": ("Рыночная годовая ставка, %", "Bozor yillik stavkasi, %", "Annual market rate, %"),
    "premium": ("Премия, UZS", "Sug‘urta mukofoti, UZS", "Premium, UZS"),
    "formula": ("Формула", "Formula", "Formula"),
    "rate_type": ("Тип ставки", "Stavka turi", "Rate type"),
    "premium_discrepancy": (
        "Отклонение премии документа, UZS",
        "Hujjat mukofotidagi farq, UZS",
        "Document premium difference, UZS",
    ),
    "comparison": ("Сверка тарифа", "Tarifni solishtirish", "Rate comparison"),
    "risk_score": ("Страховой балл", "Sug‘urta bali", "Insurance score"),
    "risk_level": ("Уровень риска", "Xatar darajasi", "Risk level"),
    "risk_multiplier": ("Множитель риска", "Xatar koeffitsiyenti", "Risk multiplier"),
    "regional_adjustment": ("Поправка региона", "Hududiy tuzatish", "Regional adjustment"),
    "loss_adjustment": ("Поправка убытков", "Zararlar bo‘yicha tuzatish", "Claims adjustment"),
    "estimate": ("Оценка, UZS", "Baholangan qiymat, UZS", "Estimate, UZS"),
    "raw_median": ("Медиана до правок, UZS", "Tuzatishlardan oldingi mediana, UZS", "Original median, UZS"),
    "method": ("Метод", "Usul", "Method"),
    "status": ("Статус", "Holat", "Status"),
    "deviation_percent": ("Отклонение, %", "Farq, %", "Deviation, %"),
    "second_method_deviation_percent": (
        "Расхождение второго метода, %",
        "Ikkinchi usuldagi farq, %",
        "Second method difference, %",
    ),
    "source": ("Источник", "Manba", "Source"),
    "document": ("Документ", "Hujjat", "Document"),
    "manual_input": (
        "Ввод сотрудника; сверьте с документами",
        "Xodim kiritgan; hujjatlar bilan solishtiring",
        "Employee input; reconcile against documents",
    ),
    "corrections": ("Правки сотрудника", "Xodim tuzatishlari", "Employee corrections"),
    "reason": ("Причина", "Sabab", "Reason"),
    "conflicts": ("Расхождения", "Tafovutlar", "Discrepancies"),
    "excluded": ("Исключённые предложения", "Chiqarib tashlangan takliflar", "Excluded comparables"),
    "product": ("Продукт", "Mahsulot", "Product"),
    "policy_version": ("Версия тарифной политики", "Tarif siyosati versiyasi", "Tariff policy version"),
    "effective_from": ("Действует с", "Amal qilish sanasi", "Effective from"),
    "losses": (
        "Убытки за три полных года",
        "Uch to‘liq yil uchun zararlar",
        "Claims for three complete years",
    ),
    "calibration": ("Утверждённая калибровка", "Tasdiqlangan kalibrlash", "Approved calibration"),
    "template": ("Версия шаблона", "Shablon versiyasi", "Template version"),
    "stale": ("УСТАРЕЛИ", "ESKIRGAN", "STALE"),
    "none": ("Нет", "Yo‘q", "None"),
    "policy": ("Правила оценки", "Baholash qoidalari", "Valuation rules"),
    "outlier_low": ("Нижняя граница медианы", "Mediananing quyi chegarasi", "Median lower bound"),
    "outlier_high": ("Верхняя граница медианы", "Mediananing yuqori chegarasi", "Median upper bound"),
    "tolerance": ("Допустимое отклонение", "Ruxsat etilgan farq", "Allowed deviation"),
    "requires_appraiser": (
        "Требуется оценщик и второй метод",
        "Baholovchi va ikkinchi usul talab qilinadi",
        "Appraiser and second method required",
    ),
    "approved_by": ("Утвердил актуарий", "Aktuariy tasdiqlagan", "Actuary approval"),
    "unapproved": (
        "Экспертная оценка, не утверждена страховщиком",
        "Ekspert bahosi, sug‘urtalovchi tasdiqlamagan",
        "Expert estimate, not insurer-approved",
    ),
    "annual": ("Годовая", "Yillik", "Annual"),
    "fixed": ("Фиксированная", "Belgilangan", "Fixed"),
    "program": ("По программе", "Dastur bo‘yicha", "Program"),
    "normative": ("По нормативному акту", "Normativ hujjat bo‘yicha", "Statutory"),
    "low": ("Низкий", "Past", "Low"),
    "moderate": ("Умеренный", "O‘rtacha", "Moderate"),
    "high": ("Высокий", "Yuqori", "High"),
    "unavailable": ("Данные недоступны", "Ma’lumot mavjud emas", "Data unavailable"),
    "confirmed": ("Стоимость подтверждена", "Qiymat tasdiqlandi", "Value confirmed"),
    "clarify": ("Стоимость нужно уточнить", "Qiymatni aniqlashtirish kerak", "Value needs clarification"),
    "below_minimum": ("Ниже минимума", "Eng kam stavkadan past", "Below minimum"),
    "above_market": ("Выше рынка", "Bozordan yuqori", "Above market"),
    "within_range": ("Внутри вилки", "Oraliq ichida", "Within range"),
    "above_minimum_market_unavailable": (
        "Не ниже минимума; рынок недоступен",
        "Eng kam stavkadan past emas; bozor ma’lumoti yo‘q",
        "At or above minimum; market unavailable",
    ),
    "purchase_less_depreciation": (
        "Цена покупки минус износ",
        "Xarid narxi minus eskirish",
        "Purchase price less depreciation",
    ),
    "appraiser_and_second_method": (
        "Отчёт оценщика и второй метод",
        "Baholovchi hisoboti va ikkinchi usul",
        "Appraiser and independent second method",
    ),
    "comparable_mean": (
        "Среднее сопоставимых предложений",
        "O‘xshash takliflarning o‘rtachasi",
        "Comparable mean",
    ),
    "blank": ("Не заполнено", "To‘ldirilmagan", "Blank"),
    "needs_review": ("Нужна проверка", "Tekshirish kerak", "Needs review"),
    "extracted": ("Извлечено правилами", "Qoidalar bilan ajratilgan", "Extracted by rules"),
    "manual": ("Ручная проверка", "Qo‘lda tekshirish", "Manual review"),
    "declared_rate": ("Тариф документа, %", "Hujjat tarifi, %", "Document rate, %"),
    "declared_premium": ("Премия документа", "Hujjat mukofoti", "Document premium"),
    "insured_organization": (
        "Страхователь (организация)",
        "Sug‘urta qildiruvchi (tashkilot)",
        "Policyholder organization",
    ),
    "insurer_organization": (
        "Страховщик (организация)",
        "Sug‘urtalovchi (tashkilot)",
        "Insurer organization",
    ),
    "contract_start": ("Дата начала", "Boshlanish sanasi", "Start date"),
    "contract_end": ("Дата окончания", "Tugash sanasi", "End date"),
    "purchase_price": ("Цена покупки", "Xarid narxi", "Purchase price"),
    "depreciation_percent": ("Износ, %", "Eskirish, %", "Depreciation, %"),
    "appraiser_value": ("Оценка оценщика", "Baholovchi qiymati", "Appraiser value"),
    "appraiser_source": ("Источник оценки", "Baholash manbasi", "Appraiser source"),
    "appraiser_date": ("Дата оценки", "Baholash sanasi", "Appraiser date"),
    "second_method_value": ("Второй метод", "Ikkinchi usul", "Second method value"),
    "second_method_source": ("Источник второго метода", "Ikkinchi usul manbasi", "Second method source"),
    "second_method_date": ("Дата второго метода", "Ikkinchi usul sanasi", "Second method date"),
    "price": ("Цена", "Narx", "Price"),
    "original_price": ("Цена до правок", "Tuzatishdan oldingi narx", "Original price"),
    "price_uzs": ("Цена, UZS", "Narx, UZS", "Price, UZS"),
    "edit_reason": ("Причина правки", "Tuzatish sababi", "Correction reason"),
    "year": ("Год", "Yil", "Year"),
    "claims": ("Страховые случаи", "Sug‘urta hodisalari", "Claims"),
    "payments": ("Выплаты", "To‘lovlar", "Payments"),
    "premiums": ("Премии", "Mukofotlar", "Premiums"),
    "contracts": ("Договоры", "Shartnomalar", "Contracts"),
    "loss_ratio": ("Убыточность", "Zararlilik", "Loss ratio"),
    "frequency": ("Частота", "Chastota", "Frequency"),
    "risk_shares": ("Доли рисков", "Xatar ulushlari", "Risk shares"),
    "underwriter": (
        "Подлежит подтверждению андеррайтером",
        "Anderrayter tasdig‘i talab qilinadi",
        "Subject to underwriter confirmation",
    ),
    "not_credit": ("Не является кредитным скорингом", "Kredit skoringi emas", "Not a credit score"),
    "no_ai": (
        "ИИ отключён; фото и сканы проверяются сотрудником вручную",
        "SI o‘chirilgan; foto va skanlarni xodim qo‘lda tekshiradi",
        "AI disabled; photos and scans require employee review",
    ),
    "check_values": (
        "Проверить суммы, сроки и источники",
        "Summalar, muddatlar va manbalarni tekshiring",
        "Check amounts, terms and sources",
    ),
    "check_conflicts": (
        "Разрешить расхождения документов",
        "Hujjatlardagi tafovutlarni hal qiling",
        "Resolve document discrepancies",
    ),
    "check_value": ("Проверить оценку стоимости", "Qiymat bahosini tekshiring", "Verify valuation"),
    "check_rates": (
        "Проверить актуальность тарифов и нормативных актов",
        "Tarif va normativ hujjatlar dolzarbligini tekshiring",
        "Verify tariff and statutory validity",
    ),
    "check_approval": (
        "Утвердить условия андеррайтером",
        "Shartlarni anderrayter tasdiqlasin",
        "Obtain underwriter approval",
    ),
    "original_language": (
        "Текст источника / оговорки сохранён на исходном языке",
        "Manba / shart matni asl tilida saqlangan",
        "Source / clause text retained in its original language",
    ),
}
WARNINGS = {
    "Поправки и страховой балл — оценка разработчика, не утверждено страховщиком": (
        "Xatar tuzatishlari va ball sug‘urtalovchi tomonidan tasdiqlanmagan",
        "Risk adjustments and score are not insurer-approved",
    ),
    "Шаблон класса отсутствует; аналитика риска недоступна": (
        "Sinf shabloni yo‘q; xatar tahlili mavjud emas",
        "No class template; risk analysis unavailable",
    ),
    "Поправки открытых данных — экспертные, не утверждены страховщиком": (
        "Ochiq ma’lumot tuzatishlari ekspert bahosi, tasdiqlanmagan",
        "Public-data adjustments are expert estimates, not insurer-approved",
    ),
    "Рыночная ставка ниже минимума компании; минимум сохраняется": (
        "Bozor stavkasi kompaniya minimumidan past; minimum saqlanadi",
        "Market rate is below company minimum; minimum is retained",
    ),
    "Ставка не определена: выберите утверждённую программу": (
        "Stavka aniqlanmagan: tasdiqlangan dasturni tanlang",
        "Rate undefined: select an approved program",
    ),
    "Ставка не определена: нет нормативной формулы": (
        "Stavka aniqlanmagan: normativ formula yo‘q",
        "Rate undefined: statutory formula unavailable",
    ),
}


def label(key, language):
    return TEXT.get(key, (key, key, key))[{"ru": 0, "uz": 1, "en": 2}[language]]


def warning(text, language):
    if language == "ru":
        return text
    return WARNINGS.get(text, (text, text))[0 if language == "uz" else 1]
