"""Static report labels; source excerpts and company clauses are preserved verbatim."""

# key: Russian, Uzbek, English
TEXT = {
    "inspection_guidance": (
        "Вопросы и проверка осмотра",
        "Ko‘rik savollari va tekshiruv",
        "Inspection questions and review",
    ),
    "ai_review_stale": (
        "Исходные данные изменились: эта проверка устарела и не обосновывает текущий расчёт",
        "Asosiy ma’lumotlar o‘zgardi: tekshiruv eskirgan va joriy hisob uchun asos emas",
        "Inputs changed: this review is stale and does not support the current calculation",
    ),
    "ai_review": ("Проверка предложений ИИ", "AI takliflarini tekshirish", "AI proposal review"),
    "ai_config_revision": ("Версия настроек ИИ", "AI sozlamalari versiyasi", "AI configuration revision"),
    "ai_accepted": ("Принято", "Qabul qilindi", "Accepted"),
    "ai_corrected": ("Исправлено", "Tuzatildi", "Corrected"),
    "ai_rejected": ("Отклонено", "Rad etildi", "Rejected"),
    "ai_quote": ("Цитата, предложенная ИИ", "AI taklif qilgan iqtibos", "AI-proposed source quote"),
    "ai_quote_visual": (
        "Цитата не проверена автоматически; требуется сверка с оригиналом",
        "Iqtibos avtomatik tekshirilmagan; asl hujjat bilan solishtirish kerak",
        "Quote not verified automatically; compare with the original",
    ),
    "registered_thefts": ("Зарегистрированные кражи", "Ro‘yxatga olingan o‘g‘riliklar", "Registered thefts"),
    "registered_robberies": ("Грабежи и разбои", "Talonchilik va bosqinchilik", "Muggings and robberies"),
    "mortality_per_mille": (
        "Смертность на 1000 населения",
        "1000 kishiga o‘limlar",
        "Deaths per 1000 population",
    ),
    "population_thousands": (
        "Население на начало года, тыс. человек",
        "Yil boshidagi aholi, ming kishi",
        "Population at start of year, thousands",
    ),
    "napp_ref_company_premiums": ("Премии компании", "Kompaniya mukofotlari", "Company premiums"),
    "napp_ref_company_payments": ("Выплаты компании", "Kompaniya to‘lovlari", "Company payments"),
    "napp_ref_claims_received": ("Претензии полученные", "Kelib tushgan da’volar", "Claims received"),
    "napp_ref_claims_paid": ("Претензии оплаченные", "To‘langan da’volar", "Claims paid"),
    "napp_ref_claims_refused": ("Претензии отклонённые", "Rad etilgan da’volar", "Claims refused"),
    "napp_ref_claims_unsettled": (
        "Претензии неурегулированные",
        "Ko‘rib chiqilmagan da’volar",
        "Unsettled claims",
    ),
    "napp_ref_bundle_premiums": (
        "Премии по набору классов",
        "Klasslar to‘plami bo‘yicha mukofotlar",
        "Class bundle premiums",
    ),
    "napp_ref_bundle_payments": (
        "Выплаты по набору классов",
        "Klasslar to‘plami bo‘yicha to‘lovlar",
        "Class bundle payments",
    ),
    "napp_ref_bundle_liabilities": (
        "Обязательства по набору классов",
        "Klasslar to‘plami bo‘yicha majburiyatlar",
        "Class bundle liabilities",
    ),
    "napp_ref_regional_premiums": (
        "Региональные премии рынка",
        "Hududiy bozor mukofotlari",
        "Regional market premiums",
    ),
    "napp_ref_regional_payments": (
        "Региональные выплаты рынка",
        "Hududiy bozor to‘lovlari",
        "Regional market payments",
    ),
    "napp_ref_inson_premiums_market_share": (
        "Доля INSON в премиях всего рынка",
        "INSONning umumiy bozor mukofotlaridagi ulushi",
        "INSON share of total market premiums",
    ),
    "napp_ref_inson_payments_market_share": (
        "Доля INSON в выплатах всего рынка",
        "INSONning umumiy bozor to‘lovlaridagi ulushi",
        "INSON share of total market payments",
    ),
    "napp_ref_inson_subdivision_premiums": (
        "Премии подразделений INSON",
        "INSON bo‘linmalari mukofotlari",
        "INSON subdivision premiums",
    ),
    "napp_ref_inson_subdivision_payments": (
        "Выплаты подразделений INSON",
        "INSON bo‘linmalari to‘lovlari",
        "INSON subdivision payments",
    ),
    "napp_ref_inson_payment_premium_ratio": (
        "INSON: выплаты / премии",
        "INSON: to‘lovlar / mukofotlar",
        "INSON: payments / premiums",
    ),
    "napp_ref_inson_region_to_company_ratio": (
        "INSON: отношение региона к компании",
        "INSON: hududning kompaniyaga nisbati",
        "INSON: regional ratio / company ratio",
    ),
    "evidence_kind": ("Тип цены", "Narx turi", "Price evidence"),
    "transaction_reference": ("Подтверждение сделки", "Bitim tasdig‘i", "Transaction evidence"),
    "asking_price": ("Цена предложения", "Taklif narxi", "Asking price"),
    "completed_sale": ("Завершённая сделка", "Yakunlangan bitim", "Completed sale"),
    "auction_start": ("Стартовая цена торгов", "Auksion boshlang‘ich narxi", "Auction starting price"),
    "reference_only": (
        "Только справочно; тариф не меняет",
        "Faqat ma’lumot uchun; tarifga ta’sir qilmaydi",
        "Reference only; does not change pricing",
    ),
    "tariff_source": (
        "Источник тарифной политики, страница",
        "Tarif siyosati manbasi, sahifa",
        "Tariff policy source, page",
    ),
    "policy_basis_reference": (
        "Основание базы и даты тарифа",
        "Tarif asosi va sanasi hujjati",
        "Rate basis and effective date evidence",
    ),
    "policy_terms_reference": ("Правила / программа", "Qoidalar / dastur", "Terms / programme"),
    "policy_approval_reference": ("Согласование с ЦО", "Bosh ofis tasdig‘i", "Head-office approval"),
    "agent_commission_percent": ("Агентское вознаграждение, %", "Agent mukofoti, %", "Agent commission, %"),
    "rnp_group": ("Учётная группа РНП", "RNP hisob guruhi", "Unearned premium reserve accounting group"),
    "rnp_scope": (
        "Указана только учётная группа. Сумма РНП и возврат премии не рассчитаны.",
        "Faqat hisob guruhi ko‘rsatilgan. RNP va mukofot qaytarilishi hisoblanmagan.",
        "Accounting classification only. Reserve amounts and premium refunds were not calculated.",
    ),
    "rate": (
        "Исходная ставка котировки, %",
        "Kotirovkaning dastlabki stavkasi, %",
        "Original quoted rate, %",
    ),
    "basis": ("Тип исходной котировки", "Dastlabki kotirovka turi", "Original quote basis"),
    "coverage": (
        "Сопоставимые условия страхования",
        "Taqqoslanadigan sug‘urta shartlari",
        "Comparable insurance coverage",
    ),
    "borrower": (
        "Заёмщик: отчёт кредитного бюро",
        "Qarz oluvchi: kredit byurosi hisoboti",
        "Borrower: credit bureau report",
    ),
    "organization_name": ("Организация-заёмщик", "Qarz oluvchi tashkilot", "Borrower organization"),
    "bureau_name": ("Кредитное бюро", "Kredit byurosi", "Credit bureau"),
    "report_date": ("Дата отчёта бюро", "Byuro hisoboti sanasi", "Bureau report date"),
    "score": ("Оценка бюро", "Byuro bahosi", "Bureau score"),
    "score_scale": ("Шкала оценки бюро", "Byuroning baholash shkalasi", "Bureau scoring scale"),
    "summary": ("Результат проверки сотрудником", "Xodim tekshiruvi natijasi", "Employee review summary"),
    "external_credit_score": (
        "Оценка перенесена из отчёта бюро сотрудником. Она не изменяет страховой балл и тариф автоматически.",
        "Baho byuro hisobotidan xodim tomonidan kiritilgan. Sug‘urta bali va tarifini avtomatik o‘zgartirmaydi.",
        "The employee transcribed the bureau score. It does not automatically change the insurance score or tariff.",
    ),
    "minimum": (
        "Нижняя граница стоимости, UZS",
        "Qiymatning quyi chegarasi, UZS",
        "Value range minimum, UZS",
    ),
    "maximum": (
        "Верхняя граница стоимости, UZS",
        "Qiymatning yuqori chegarasi, UZS",
        "Value range maximum, UZS",
    ),
    "purchase_source": ("Источник цены покупки", "Xarid narxi manbasi", "Purchase price source"),
    "purchase_date": (
        "Дата источника цены покупки",
        "Xarid narxi manbasi sanasi",
        "Purchase price source date",
    ),
    "missing_evidence": (
        "Не хватает подтверждения",
        "Tasdiqlovchi ma’lumot yetishmaydi",
        "Missing valuation evidence",
    ),
    "term_date_convention": (
        "Разница дат не включает дату окончания; иной срок объясняется причиной исправления.",
        "Sanalar farqi tugash kunini hisobga olmaydi; boshqa muddat tuzatish sababi bilan izohlanadi.",
        "Date difference excludes the end date; a different term requires a correction reason.",
    ),
    "date": ("Дата", "Sana", "Date"),
    "author": ("Автор", "Muallif", "Author"),
    "insured_sum": ("Страховая сумма", "Sug‘urta summasi", "Insured sum"),
    "object_value": ("Стоимость объекта", "Obyekt qiymati", "Object value"),
    "region": ("Регион", "Hudud", "Region"),
    "term_days": ("Срок, дней", "Muddat, kun", "Term, days"),
    "object_description": ("Объект страхования", "Sug‘urta obyekti", "Insured object"),
    "minimum_rate": ("Минимальная ставка, %", "Eng kam stavka, %", "Minimum rate, %"),
    "recommended_rate": ("Рекомендуемая ставка, %", "Tavsiya etilgan stavka, %", "Recommended rate, %"),
    "annualized_rate": ("Годовой эквивалент, %", "Yillik ekvivalent, %", "Annual equivalent, %"),
    "annual_market_rate": ("Рыночная годовая ставка, %", "Bozor yillik stavkasi, %", "Annual market rate, %"),
    "premium": ("Премия, UZS", "Sug‘urta mukofoti, UZS", "Premium, UZS"),
    "formula": ("Формула", "Formula", "Formula"),
    "rate_type": ("Тип ставки", "Stavka turi", "Rate type"),
    "premium_discrepancy": (
        "Отклонение премии документа, UZS",
        "Hujjat mukofotidagi farq, UZS",
        "Document premium difference, UZS",
    ),
    "comparison": ("Сверка тарифа", "Tarifni solishtirish", "Rate comparison"),
    "risk_score": ("Страховой балл", "Sug‘urta bali", "Insurance score"),
    "risk_level": ("Уровень риска", "Xatar darajasi", "Risk level"),
    "risk_multiplier": ("Множитель риска", "Xatar koeffitsiyenti", "Risk multiplier"),
    "regional_adjustment": ("Поправка региона", "Hududiy tuzatish", "Regional adjustment"),
    "loss_adjustment": ("Поправка убытков", "Zararlar bo‘yicha tuzatish", "Claims adjustment"),
    "estimate": ("Оценка, UZS", "Baholangan qiymat, UZS", "Estimate, UZS"),
    "raw_median": ("Медиана до правок, UZS", "Tuzatishlardan oldingi mediana, UZS", "Original median, UZS"),
    "method": ("Метод", "Usul", "Method"),
    "status": ("Статус", "Holat", "Status"),
    "deviation_percent": ("Отклонение, %", "Farq, %", "Deviation, %"),
    "second_method_deviation_percent": (
        "Расхождение второго метода, %",
        "Ikkinchi usuldagi farq, %",
        "Second method difference, %",
    ),
    "source": ("Источник", "Manba", "Source"),
    "document": ("Документ", "Hujjat", "Document"),
    "manual_input": (
        "Ввод сотрудника; сверьте с документами",
        "Xodim kiritgan; hujjatlar bilan solishtiring",
        "Employee input; reconcile against documents",
    ),
    "corrections": ("Правки сотрудника", "Xodim tuzatishlari", "Employee corrections"),
    "reason": ("Причина", "Sabab", "Reason"),
    "conflicts": ("Расхождения", "Tafovutlar", "Discrepancies"),
    "excluded": ("Исключённые предложения", "Chiqarib tashlangan takliflar", "Excluded comparables"),
    "product": ("Продукт", "Mahsulot", "Product"),
    "policy_version": ("Версия тарифной политики", "Tarif siyosati versiyasi", "Tariff policy version"),
    "effective_from": ("Действует с", "Amal qilish sanasi", "Effective from"),
    "losses": (
        "Убытки за три полных года",
        "Uch to‘liq yil uchun zararlar",
        "Claims for three complete years",
    ),
    "calibration": ("Утверждённая калибровка", "Tasdiqlangan kalibrlash", "Approved calibration"),
    "template": ("Версия шаблона", "Shablon versiyasi", "Template version"),
    "stale": ("УСТАРЕЛИ", "ESKIRGAN", "STALE"),
    "none": ("Нет", "Yo‘q", "None"),
    "policy": ("Правила оценки", "Baholash qoidalari", "Valuation rules"),
    "outlier_low": ("Нижняя граница медианы", "Mediananing quyi chegarasi", "Median lower bound"),
    "outlier_high": ("Верхняя граница медианы", "Mediananing yuqori chegarasi", "Median upper bound"),
    "tolerance": ("Допустимое отклонение", "Ruxsat etilgan farq", "Allowed deviation"),
    "requires_appraiser": (
        "Требуется оценщик и второй метод",
        "Baholovchi va ikkinchi usul talab qilinadi",
        "Appraiser and second method required",
    ),
    "approved_by": ("Утвердил актуарий", "Aktuariy tasdiqlagan", "Actuary approval"),
    "unapproved": (
        "Экспертная оценка, не утверждена страховщиком",
        "Ekspert bahosi, sug‘urtalovchi tasdiqlamagan",
        "Expert estimate, not insurer-approved",
    ),
    "annual": ("Годовая", "Yillik", "Annual"),
    "fixed": ("Фиксированная", "Belgilangan", "Fixed"),
    "program": ("По программе", "Dastur bo‘yicha", "Program"),
    "normative": ("По нормативному акту", "Normativ hujjat bo‘yicha", "Statutory"),
    "low": ("Низкий", "Past", "Low"),
    "moderate": ("Умеренный", "O‘rtacha", "Moderate"),
    "high": ("Высокий", "Yuqori", "High"),
    "unavailable": ("Данные недоступны", "Ma’lumot mavjud emas", "Data unavailable"),
    "confirmed": ("Стоимость подтверждена", "Qiymat tasdiqlandi", "Value confirmed"),
    "clarify": ("Стоимость нужно уточнить", "Qiymatni aniqlashtirish kerak", "Value needs clarification"),
    "below_minimum": ("Ниже минимума", "Eng kam stavkadan past", "Below minimum"),
    "above_market": ("Выше рынка", "Bozordan yuqori", "Above market"),
    "within_range": ("Внутри вилки", "Oraliq ichida", "Within range"),
    "above_minimum_market_unavailable": (
        "Не ниже минимума; рынок недоступен",
        "Eng kam stavkadan past emas; bozor ma’lumoti yo‘q",
        "At or above minimum; market unavailable",
    ),
    "purchase_less_depreciation": (
        "Цена покупки минус износ",
        "Xarid narxi minus eskirish",
        "Purchase price less depreciation",
    ),
    "appraiser_and_second_method": (
        "Отчёт оценщика и второй метод",
        "Baholovchi hisoboti va ikkinchi usul",
        "Appraiser and independent second method",
    ),
    "comparable_mean": (
        "Среднее сопоставимых предложений",
        "O‘xshash takliflarning o‘rtachasi",
        "Comparable mean",
    ),
    "blank": ("Не заполнено", "To‘ldirilmagan", "Blank"),
    "needs_review": ("Нужна проверка", "Tekshirish kerak", "Needs review"),
    "extracted": ("Извлечено правилами", "Qoidalar bilan ajratilgan", "Extracted by rules"),
    "manual": ("Ручная проверка", "Qo‘lda tekshirish", "Manual review"),
    "declared_rate": ("Тариф документа, %", "Hujjat tarifi, %", "Document rate, %"),
    "declared_premium": ("Премия документа", "Hujjat mukofoti", "Document premium"),
    "insured_organization": (
        "Страхователь (организация)",
        "Sug‘urta qildiruvchi (tashkilot)",
        "Policyholder organization",
    ),
    "insurer_organization": (
        "Страховщик (организация)",
        "Sug‘urtalovchi (tashkilot)",
        "Insurer organization",
    ),
    "contract_start": ("Дата начала", "Boshlanish sanasi", "Start date"),
    "contract_end": ("Дата окончания", "Tugash sanasi", "End date"),
    "purchase_price": ("Цена покупки", "Xarid narxi", "Purchase price"),
    "depreciation_percent": ("Износ, %", "Eskirish, %", "Depreciation, %"),
    "appraiser_value": ("Оценка оценщика", "Baholovchi qiymati", "Appraiser value"),
    "appraiser_source": ("Источник оценки", "Baholash manbasi", "Appraiser source"),
    "appraiser_date": ("Дата оценки", "Baholash sanasi", "Appraiser date"),
    "second_method_value": ("Второй метод", "Ikkinchi usul", "Second method value"),
    "second_method_source": ("Источник второго метода", "Ikkinchi usul manbasi", "Second method source"),
    "second_method_date": ("Дата второго метода", "Ikkinchi usul sanasi", "Second method date"),
    "price": ("Цена", "Narx", "Price"),
    "original_price": ("Цена до правок", "Tuzatishdan oldingi narx", "Original price"),
    "price_uzs": ("Цена, UZS", "Narx, UZS", "Price, UZS"),
    "edit_reason": ("Причина правки", "Tuzatish sababi", "Correction reason"),
    "year": ("Год", "Yil", "Year"),
    "claims": ("Страховые случаи", "Sug‘urta hodisalari", "Claims"),
    "payments": ("Выплаты", "To‘lovlar", "Payments"),
    "premiums": ("Премии", "Mukofotlar", "Premiums"),
    "contracts": ("Договоры", "Shartnomalar", "Contracts"),
    "loss_ratio": ("Убыточность", "Zararlilik", "Loss ratio"),
    "frequency": ("Частота", "Chastota", "Frequency"),
    "risk_shares": ("Доли рисков", "Xatar ulushlari", "Risk shares"),
    "underwriter": (
        "Подлежит подтверждению андеррайтером",
        "Anderrayter tasdig‘i talab qilinadi",
        "Subject to underwriter confirmation",
    ),
    "not_credit": ("Не является кредитным скорингом", "Kredit skoringi emas", "Not a credit score"),
    "human_review": (
        "Значения документов проверяются сотрудником; предложения ИИ требуют ручного подтверждения",
        "Hujjat qiymatlarini xodim tekshiradi; AI takliflari qo‘lda tasdiqlanadi",
        "Document values are reviewed by staff; AI suggestions require human confirmation",
    ),
    "check_values": (
        "Проверить суммы, сроки и источники",
        "Summalar, muddatlar va manbalarni tekshiring",
        "Check amounts, terms and sources",
    ),
    "check_conflicts": (
        "Разрешить расхождения документов",
        "Hujjatlardagi tafovutlarni hal qiling",
        "Resolve document discrepancies",
    ),
    "check_value": ("Проверить оценку стоимости", "Qiymat bahosini tekshiring", "Verify valuation"),
    "check_rates": (
        "Проверить актуальность тарифов и нормативных актов",
        "Tarif va normativ hujjatlar dolzarbligini tekshiring",
        "Verify tariff and statutory validity",
    ),
    "check_approval": (
        "Утвердить условия андеррайтером",
        "Shartlarni anderrayter tasdiqlasin",
        "Obtain underwriter approval",
    ),
    "original_language": (
        "Текст источника / оговорки сохранён на исходном языке",
        "Manba / shart matni asl tilida saqlangan",
        "Source / clause text retained in its original language",
    ),
}
WARNINGS = {
    "Поправки риска не применены: шаблон не утверждён страховщиком": (
        "Xatar tuzatishlari qo‘llanilmadi: shablon sug‘urtalovchi tomonidan tasdiqlanmagan",
        "Risk adjustments were not applied: the template lacks insurer approval",
    ),
    "База тарифа — сумма лимита; в поле страховой суммы должен быть указан лимит": (
        "Tarif asosi limit summasi; sug‘urta summasi maydonida limit ko‘rsatilishi kerak",
        "The rate applies to the limit; enter the limit in the insured sum field",
    ),
    "Региональная поправка не рассчитана: нет актуальных данных, связанных с правилами для этого объекта": (
        "Hududiy tuzatish hisoblanmadi: ushbu obyekt qoidalariga bog‘langan dolzarb ma’lumot yo‘q",
        "Regional adjustment unavailable: no current data is linked to rules for this object",
    ),
    "Рыночная годовая ставка недоступна: требуется сопоставимая котировка с источником и датой": (
        "Bozor yillik stavkasi yo‘q: manbasi va sanasi ko‘rsatilgan taqqoslanadigan kotirovka kerak",
        "Annual market rate unavailable: provide a comparable quote with its source and date",
    ),
    "Поправки и страховой балл — оценка разработчика, не утверждено страховщиком": (
        "Xatar tuzatishlari va ball sug‘urtalovchi tomonidan tasdiqlanmagan",
        "Risk adjustments and score are not insurer-approved",
    ),
    "Шаблон класса отсутствует; аналитика риска недоступна": (
        "Sinf shabloni yo‘q; xatar tahlili mavjud emas",
        "No class template; risk analysis unavailable",
    ),
    "Поправки открытых данных — экспертные, не утверждены страховщиком": (
        "Ochiq ma’lumot tuzatishlari ekspert bahosi, tasdiqlanmagan",
        "Public-data adjustments are expert estimates, not insurer-approved",
    ),
    "Рыночная ставка ниже минимума компании; минимум сохраняется": (
        "Bozor stavkasi kompaniya minimumidan past; minimum saqlanadi",
        "Market rate is below company minimum; minimum is retained",
    ),
    "Ставка не определена: выберите утверждённую программу": (
        "Stavka aniqlanmagan: tasdiqlangan dasturni tanlang",
        "Rate undefined: select an approved program",
    ),
    "Ставка не определена: нет нормативной формулы": (
        "Stavka aniqlanmagan: normativ formula yo‘q",
        "Rate undefined: statutory formula unavailable",
    ),
}


def label(key, language):
    return TEXT.get(key, (key, key, key))[{"ru": 0, "uz": 1, "en": 2}[language]]


def warning(text, language):
    if language == "ru":
        return text
    return WARNINGS.get(text, (text, text))[0 if language == "uz" else 1]
