"""Version public legal and risk source documents"""

import sqlalchemy as sa
from alembic import op

revision = "5e201dfdd126"
down_revision = "6bb8d3325463"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("channel_code", sa.String(length=60), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_code"],
            ["channels.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_public_references_channel_code"), "public_references", ["channel_code"], unique=False
    )
    op.create_index(
        op.f("ix_public_references_source_url"), "public_references", ["source_url"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_references_source_url"), table_name="public_references")
    op.drop_index(op.f("ix_public_references_channel_code"), table_name="public_references")
    op.drop_table("public_references")
    # ### end Alembic commands ###
